### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by Durza404** [ModTheGungeon/ETGMod.Installer#17]
ETGMod Installer v17.3.8
Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at ETGModInstaller.ETGModder.getLength(String url)
   at ETGModInstaller.ETGModder.Download(InstallerWindow ins, String url)
   at ETGModInstaller.ETGModder.DownloadCached(InstallerWindow ins, String url, String cached)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

i have gog games version not steam version but my version is up to date

**Comment by Durza404** [comment]
nvm i figured it out. i put the installer in offline mode and downloaded the api zip from here
