### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ju1095** [ModTheGungeon/ETGMod.Installer#19]
Log:
ETGMod Installer v17.3.8
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Reading from cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll

System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

Can I get some help please? The mod was working until the latest update of ETG (1.14h3)

**Comment by 0x0ade** [comment]
Please try to run the installer again. It will download the newest "base" build automagically.

I'm not actively working on ETGMod again, but a recent MonoMod update made me recompile ETGMod.

Please check out [this Reddit thread + the "EDIT 2" at the top.](https://www.reddit.com/r/EnterTheGungeon/comments/75qqe9/status_of_mod_the_gungeon/)
