### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by masterhand121** [ModTheGungeon/ETGMod.Installer#2]
The installer keeps giving this error as soon as a launch it.

ETGMod Installer v16.12.16.0
Something went horribly wrong:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at ETGModInstaller.RepoHelper.GetAPIMods()
at ETGModInstaller.InstallerWindow.DownloadModsList()

**Comment by zatherz** [comment]
Do you still experience this issue?

**Comment by masterhand121** [comment]
yes

**Comment by zatherz** [comment]
Does this page work for you? https://modthegungeon.eu/modlist.txt (it should be a blank page, but not a 404/503/whatever error)

**Comment by masterhand121** [comment]
Yeah. I get a blank page. I even tried adding a specific rule in my firewall to let the installer through.

**Comment by 677345** [comment]
I get this same issue, no idea the cause

**Comment by Spectralniy** [comment]
У меня такая - же проблемма но эта ссылка - https://modthegungeon.eu/modlist.txt у меня отображается!

I have this problemm to, but i see this https://modthegungeon.eu/modlist.txt link!
