### ISSUE TITLE
Error with the installer

### ISSUE THREAD

**Issue by Miokanode** [ModTheGungeon/ETGMod.Installer#21]
MonoMod.RelinkFailedException: MonoMod failed relinking CustomSynergyType (context: System.Void ETGModConsole::DumpSynergies(System.String[])) ---> MonoMod.RelinkTargetNotFoundException: MonoMod relinker failed finding CustomSynergyType (context: System.Void ETGModConsole::DumpSynergies(System.String[]))
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   --- End of inner exception stack trace ---
   at MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
MonoMod.RelinkFailedException: MonoMod failed relinking CustomSynergyType (context: System.Void ETGModConsole::DumpSynergies(System.String[])) ---> MonoMod.RelinkTargetNotFoundException: MonoMod relinker failed finding CustomSynergyType (context: System.Void ETGModConsole::DumpSynergies(System.String[]))
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   --- End of inner exception stack trace ---
   at MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

I get this error every time i try to mod ETG.

**Comment by 0x0ade** [comment]
What version of Gungeon do you have?

**Comment by Miokanode** [comment]
I have the version 1.0.11.

**Comment by 0x0ade** [comment]
That's quite outdated.

1. In the installer, press the red X right to the install button
2. Leave any betas on Steam
3. Update the game

Then try again. I'll close the issue as it's not an installer issue.
