### ISSUE TITLE
When I try to install the executable file vanishes 

### ISSUE THREAD

**Issue by beefyturtle** [ModTheGungeon/ETGMod.Installer#26]
When I open the installer I see this

ETGMod Installer v17.10.19
Something went horribly wrong:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at ETGModInstaller.RepoHelper.GetAPIMods()
   at ETGModInstaller.InstallerWindow.DownloadModsList()

But when I try to install I see this

Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Net.WebClient.OpenRead(String address)
   at ETGModInstaller.ETGModder.Download(InstallerWindow ins, String url)
   at ETGModInstaller.ETGModder.DownloadCached(InstallerWindow ins, String url, String cached)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by brettonI** [comment]
I'm having the same issue I haven't found any solution to this
