### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ThisMans** [ModTheGungeon/ETGMod.Installer#34]
ETGMod Installer v17.10.19
Something went horribly wrong:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at ETGModInstaller.RepoHelper.GetAPIMods()
   at ETGModInstaller.InstallerWindow.DownloadModsList()
Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.bin
WARNING: Backup not found for EtG.bin
Reverting: Assembly-CSharp.dll
Reverting: EtG.exe
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll

Now comes the real "modding" / patching process.
It may seem like the Installer may be stuck sometimes. Go make
yourself a coffee in the meantime - it doesn't get stuck.
It may *crash*, though - and in this case, debug stuff appears
here. Please put that debug stuff onto http://pastebin.com/ and
send it to @0x0ade on Twitter or the #modding channel in Discord.

System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ETGModInstaller.ETGModder.PatchExe(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

anyone know why this is happening?

**Comment by ThisMans** [comment]
nvm

**Comment by ThisMans** [comment]
know i just get a black screen
