### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by HardyThePirate** [ModTheGungeon/ETGMod.Installer#35]
this keeps showing up 
Downloading http://modthegungeon.github.io/ETGMOD.zip...
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Net.WebClient.OpenRead(String address)
   at ETGModInstaller.ETGModder.Download(InstallerWindow ins, String url)
   at ETGModInstaller.ETGModder.DownloadCached(InstallerWindow ins, String url, String cached)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by Moongull** [comment]
https://www.youtube.com/watch?v=-dKKi4ey8wY  <That
