### ISSUE TITLE
When I start the installer the backends won't load

### ISSUE THREAD

**Issue by beefyturtle** [ModTheGungeon/ETGMod.Installer#36]
ETGMod Installer v17.10.19
Something went horribly wrong:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at ETGModInstaller.RepoHelper.GetAPIMods()
   at ETGModInstaller.InstallerWindow.DownloadModsList()

All I get is this in the log and then when I go to try and select my backends it says something went wrong -see the log.

**Comment by Moongull** [comment]
https://www.youtube.com/watch?v=-dKKi4ey8wY Follow This
