### ISSUE TITLE
ETG Mod installer error

### ISSUE THREAD

**Issue by Weftin** [ModTheGungeon/ETGMod.Installer#45]
ETGMod Installer v17.10.19
Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
WARNING: Backup not found for EtG.exe
Reverting: Assembly-CSharp.dll
System.UnauthorizedAccessException: Access to the path 'D:\Programs\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at ETGModInstaller.ETGModder.Uninstall(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

I've gone through the regedit, three separate restarts and reinstall to no avail

**Comment by gpere** [comment]
Try running as admin

**Comment by Weftin** [comment]
Tried that, same error

**Comment by gpere** [comment]
I know how to fix it; you need to go to an earlier version of MtG

**Comment by Weftin** [comment]
Attempted on v17.02.22.1, v16.12.16, and v16.07.24. Same error each time, how far back should I go?
