### ISSUE TITLE
Error On Installation

### ISSUE THREAD

**Issue by gpere** [ModTheGungeon/ETGMod.Installer#47]
ETGMod Installer v17.10.19
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Reading from cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/YamlDotNet.dll: 199680 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19456 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/System.Xml.Linq.dll: 58880 bytes
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 313344 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: InstallerVersion.txt: 9 bytes
Found version file.
ETGMOD/ found.
Extracting: ETGMOD/YamlDotNet.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/System.Xml.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll
Extracting: ETGMOD/I18N.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/System.Xml.Linq.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.Linq.dll
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.West.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/PEG.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll

Now comes the real "modding" / patching process.
It may seem like the Installer may be stuck sometimes. Go make
yourself a coffee in the meantime - it doesn't get stuck.
It may *crash*, though - and in this case, debug stuff appears
here. Please put that debug stuff onto http://pastebin.com/ and
send it to @0x0ade on Twitter or the #modding channel in Discord.

MonoMod.RelinkTargetNotFoundException: MonoMod cannot map dependency UnityEngine.Base.mm.dll -> ((UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null), (UnityEngine.CoreModule)) - not found
   at MonoMod.MonoModder.DefaultMissingDependencyResolver(MonoModder mod, ModuleDefinition main, String name, String fullName)
   at MonoMod.MonoModder.MapDependency(ModuleDefinition main, String name, String fullName)
   at MonoMod.MonoModder.MapDependency(ModuleDefinition main, AssemblyNameReference dep)
   at MonoMod.MonoModder.MapDependencies(ModuleDefinition main)
   at MonoMod.MonoModder.MapDependencies()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
MonoMod.RelinkTargetNotFoundException: MonoMod cannot map dependency UnityEngine.Base.mm.dll -> ((UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null), (UnityEngine.CoreModule)) - not found
   at MonoMod.MonoModder.DefaultMissingDependencyResolver(MonoModder mod, ModuleDefinition main, String name, String fullName)
   at MonoMod.MonoModder.MapDependency(ModuleDefinition main, String name, String fullName)
   at MonoMod.MonoModder.MapDependency(ModuleDefinition main, AssemblyNameReference dep)
   at MonoMod.MonoModder.MapDependencies(ModuleDefinition main)
   at MonoMod.MonoModder.MapDependencies()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by Baennon** [comment]
Same issue here

**Comment by keegsman10** [comment]
same here they dont offer support sadly'
