### ISSUE TITLE
System.Xml.dll being used by another process

### ISSUE THREAD

**Issue by ElusiveKoala** [ModTheGungeon/ETGMod.Installer#7]
ETGMod Installer v17.2.22.1
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Reading from cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Stream zs)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Byte[] data)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by ElusiveKoala** [comment]
Well problem seems fairly straightforward but don't know which process is using it.
Steam version, Windows 10

**Comment by Questpurex10** [comment]
I also have this problem! I am using the latest version/update of ETG and ModTG.
Here is my ETGMod.Installer log.
`ETGMod Installer v17.2.27.0
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
Download complete, 1669.59 KiB in 3.19 s.
Writing to cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll
System.IO.IOException: The process cannot access the file 'C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Stream zs)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Byte[] data)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)
`
