### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by TheE1337** [ModTheGungeon/ETGMod.Installer#8]
![untitled](https://cloud.githubusercontent.com/assets/26185634/23579352/f806156e-00a8-11e7-9401-fbd79949c0c8.png)

Log:
ETGMod Installer v17.2.27.0
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Reading from cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll
System.IO.IOException: The process cannot access the file 'C:\Users\Nate\Documents\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Stream zs)
   at ETGModInstaller.ETGModder.UnzipMod(InstallerWindow ins, Byte[] data)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by ExorcistF1** [comment]
![default](https://cloud.githubusercontent.com/assets/8391676/23641533/8f9316e4-0305-11e7-94dd-ad89f84414ee.JPG)
try to delete select files

**Comment by ThatguywhocanfixtheproblemwithMtG** [comment]
try to add "Enter the Gungeon"  folder to C:\Users\Nate\Documents

**Comment by ThatguywhocanfixtheproblemwithMtG** [comment]
I hope that will help
