### ISSUE TITLE
help so many errors

### ISSUE THREAD

**Issue by TacoUpgrade** [ModTheGungeon/ETGMod.Installer#9]
i fixed the frist error but i can't fix this one

ETGMod Installer v17.3.8
Entering the Modgeon
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
Download complete, 1669.59 KiB in 1.09 s.
Writing to cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll

Now comes the real "modding" / patching process.
It may seem like the Installer may be stuck sometimes. Go make
yourself a coffee in the meantime - it doesn't get stuck.
It may *crash*, though - and in this case, debug stuff appears
here. Please put that debug stuff onto http://pastebin.com/ and
send it to @0x0ade on Twitter or the #modding channel in Discord.

System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

i have used v17.2.27.0 and v17.03.08

**Comment by 0x0ade** [comment]
Have you tried v17.02.22.1?

TacoUpgrade <notifications@github.com> schrieb am Mi., 8. März 2017 um
23:44 Uhr:

**Comment by TacoUpgrade** [comment]
just did no luck

**Comment by 0x0ade** [comment]
Does that result in the exactly same error?

TacoUpgrade <notifications@github.com> schrieb am Mi., 8. März 2017 um
23:52 Uhr:

**Comment by TacoUpgrade** [comment]
yes

**Comment by 0x0ade** [comment]
I see you're using the GOG version, so you won't be able to simply "verify files". Please reinstall the game completely (your savefile / progress is stored separately) and retry with the v17.02.22.1 installler.

If it still happens, go to the Gungeon directory, EtG_Data, Managed. Drag ETGModInstallLog.txt in here to upload it.

**Comment by TacoUpgrade** [comment]
[ETGModInstallLog.txt](https://github.com/ModTheGungeon/ETGMod.Installer/files/829216/ETGModInstallLog.txt)

**Comment by 0x0ade** [comment]
Unfortunately I can't see the cause - seems like you're currently out of luck :/

v17.03.08 contains a few other fixes, but you first tried that and it still caused the error to appear for you.

The only last thing I could advise you to do for now is to [install the .NET Framework 4.5](https://www.microsoft.com/en-US/download/details.aspx?id=30653) (make sure you pick the system's language). I've seen the lack of the .NET Framework doing weird stuff with MonoMod (my installer core) before...

**Comment by TacoUpgrade** [comment]
thanks for the help i will just try it later when i get the steam version
